{
 "title": "Speedtest Dashboard",
 "description": "A dashboard for Prometheus Speedtest Exporter",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Speedtest Timeline",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "download_speed_bps", "legendFormat": "Download Speed" },
    { "expr": "upload_speed_bps", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "Current Ping Latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_ms", "legendFormat": "Ping Latency" }
   ]
  },
  {
   "title": "Current Download Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_speed_bps", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Current Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upload_speed_bps", "legendFormat": "Upload Speed" }
   ]
  }
 ]
}